import type { Listing, Recipient } from "./domain";

// Invented businesses, requirements and quotes for a reproducible demo. Not live demand.
export const RECIPIENTS: Recipient[] = [
  {
    id: "r-mushroom",
    name: "Loop Mushroom Co.",
    kind: "Mushroom grower",
    initials: "LM",
    location: "Brunswick",
    lat: -37.767,
    lng: 144.972,
    materials: ["grounds"],
    pathway: "Mushroom substrate",
    demand: "demo_active",
    minKg: 5,
    capacityKg: 100,
    maxAgeHours: 24,
    requiresChilled: true,
    requiresSealed: false,
    pricePerKg: 0.4,
    serviceFeeAud: 0,
    collects: true,
    description:
      "Needs clean, chilled grounds. Collection included in the sample offer.",
    fixture: true,
  },
  {
    id: "r-compost",
    name: "Northside Soil Collective",
    kind: "Compost processor",
    initials: "NS",
    location: "Coburg",
    lat: -37.742,
    lng: 144.966,
    materials: ["grounds", "chaff", "husks", "pulp"],
    pathway: "Controlled composting",
    demand: "demo_active",
    minKg: 10,
    capacityKg: 250,
    maxAgeHours: 72,
    requiresChilled: false,
    requiresSealed: false,
    pricePerKg: 0,
    serviceFeeAud: 5,
    collects: true,
    description:
      "Accepts uncontaminated material. Sample collection fee: $5 per batch.",
    fixture: true,
  },
  {
    id: "r-cafe",
    name: "Second Shot Café",
    kind: "Café",
    initials: "SS",
    location: "Carlton",
    lat: -37.798,
    lng: 144.967,
    materials: ["beans"],
    pathway: "Brewed as coffee",
    demand: "demo_active",
    minKg: 1,
    capacityKg: 25,
    maxAgeHours: null,
    requiresChilled: false,
    requiresSealed: true,
    pricePerKg: 12,
    serviceFeeAud: 0,
    collects: true,
    description:
      "Sample buyer for sealed, labelled beans within best-before. Buyer still checks the batch.",
    fixture: true,
  },
  {
    id: "r-nearby",
    name: "Freshcap Studio",
    kind: "Mushroom grower",
    initials: "FS",
    location: "Fitzroy",
    lat: -37.795,
    lng: 144.981,
    materials: ["grounds"],
    pathway: "Mushroom substrate",
    demand: "demo_active",
    minKg: 50,
    capacityKg: 150,
    maxAgeHours: 12,
    requiresChilled: true,
    requiresSealed: false,
    pricePerKg: 0.6,
    serviceFeeAud: 0,
    collects: true,
    description:
      "Closer, but sample minimum is 50 kg and freshness limit is 12 hours.",
    fixture: true,
  },
  {
    id: "r-material",
    name: "Circular Material Lab",
    kind: "Material processor",
    initials: "CM",
    location: "Richmond",
    lat: -37.822,
    lng: 145.003,
    materials: ["grounds", "chaff", "husks"],
    pathway: "Material research / processing",
    demand: "prospect",
    minKg: 20,
    capacityKg: 100,
    maxAgeHours: 168,
    requiresChilled: false,
    requiresSealed: false,
    pricePerKg: null,
    serviceFeeAud: 0,
    collects: false,
    description:
      "Demonstration prospect only. Acceptance, processing conditions and a quote need confirmation.",
    fixture: true,
  },
];
export function seedListings(now = new Date()): Listing[] {
  const time = (hours: number) =>
    new Date(now.getTime() + hours * 3600000).toISOString();
  const date = (days: number) =>
    new Date(now.getTime() + days * 86400000).toISOString().slice(0, 10);
  const common = {
    supplierId: "c-demo",
    fixture: true,
    origin: "cafe" as const,
    location: "Fitzroy, Melbourne",
    lat: -37.798,
    lng: 144.979,
    availableAt: time(-0.1),
    createdAt: time(-2),
    condition: "clean" as const,
    disposalEvidence: "Sample fixed disposal bill; no avoided cost assumed.",
    avoidedDisposalPerKg: 0,
    handlingAud: 2,
    supplierTransportAud: 0,
    notes:
      "Demo batch from Common Ground Café. Quantities and costs are sample inputs.",
  };
  return [
    {
      ...common,
      id: "l-grounds",
      title: "This morning’s coffee grounds",
      material: "grounds",
      quantityKg: 30,
      availableKg: 30,
      collectedAt: time(-3),
      expiresAt: time(10),
      storage: "chilled",
      packaging: "not_applicable",
      roastDate: null,
      bestBefore: null,
    },
    {
      ...common,
      id: "l-beans",
      title: "Surplus house-blend beans",
      material: "beans",
      quantityKg: 6,
      availableKg: 6,
      collectedAt: time(-4),
      expiresAt: time(48),
      storage: "dry_sealed",
      packaging: "sealed_labelled",
      roastDate: date(-10),
      bestBefore: date(50),
      handlingAud: 0,
    },
    {
      ...common,
      id: "l-pool",
      title: "Tomorrow’s grounds batch",
      material: "grounds",
      quantityKg: 24,
      availableKg: 24,
      collectedAt: time(18),
      availableAt: time(20),
      expiresAt: time(28),
      storage: "chilled",
      packaging: "not_applicable",
      roastDate: null,
      bestBefore: null,
      notes:
        "Demo future batch. Available window differs from this morning’s batch; do not silently pool them.",
    },
  ];
}
